sourceId=cancer_biomarkers:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [source_type=constant:targets, target_type=constant:diseases, datasourceId, score, year, id]

sourceId=chembl:
  - source: diseaseId
    target: targetId
    relation_name: clinical_trial
    props: [source_type=constant:diseases, target_type=constant:targets, datasourceId, score, year, id]

  - source: drugId
    target: targetId
    relation_name: modulated_by
    props: [source_type=constant:molecule, target_type=constant:targets, datasourceId, score, year, id]

sourceId=reactome:
  - source: targetId
    target: diseaseId
    relation: datatypeId
    props: [source_type=constant:targets, target_type=constant:diseases, datasourceId, score, year, id]
    
  - source: targetId
    target: pathways.id
    relation_name: involved_in
    props: [source_type=constant:targets, target_type=constant:reactome, datasourceId, score, year, id]

  - source: diseaseId
    target: pathways.id
    relation: datatypeId
    relation_name: associated_with
    props: [source_type=constant:diseases, target_type=constant:reactome, datasourceId, score, year, id]

sourceId=clingen:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [source_type=constant:targets, target_type=constant:diseases, datasourceId, score, year, id]

sourceId=eva:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [source_type=constant:targets, target_type=constant:diseases, datasourceId, score, year, id]

sourceId=gene_burden:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [source_type=constant:targets, target_type=constant:diseases, datasourceId, score, year, id]

sourceId=intogen:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [source_type=constant:targets, target_type=constant:diseases, datasourceId, score, year, id]

sourceId=slapenrich:
  - source: targetId
    target: diseaseId
    relation: datatypeId
    props: [source_type=constant:targets, target_type=constant:diseases, datasourceId, score, year, id]

  - source: targetId
    target: pathways.id
    relation_name: involved_in
    props: [source_type=constant:targets, target_type=constant:reactome, datasourceId, score, year, id]

  - source: diseaseId
    target: pathways.id
    relation_name: associated_with
    props: [source_type=constant:disease, target_type=constant:reactome, datasourceId, score, year, id]

sourceId=crispr:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [source_type=constant:targets, target_type=constant:diseases, datasourceId, score, year, id]

sourceId=eva_somatic:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [source_type=constant:targets, target_type=constant:diseases, datasourceId, score, year, id]

sourceId=genomics_england:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [source_type=constant:targets, target_type=constant:diseases, datasourceId, score, year, id]

sourceId=orphanet:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [source_type=constant:targets, target_type=constant:diseases, datasourceId, score, year, id]

sourceId=sysbio:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [source_type=constant:targets, target_type=constant:diseases, datasourceId, score, year, id]

sourceId=cancer_gene_census:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [source_type=constant:targets, target_type=constant:diseases, datasourceId, score, year, id]

sourceId=crispr_screen:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [source_type=constant:targets, target_type=constant:diseases, cellType, datasourceId, score, year, id]

sourceId=expression_atlas:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [source_type=constant:targets, target_type=constant:diseases, datasourceId, score, year, id]

sourceId=progeny:
  - source: targetId
    target: diseaseId
    relation: datatypeId
    props: [source_type=constant:targets, target_type=constant:diseases, datasourceId, score, year, id]

  - source: targetId
    target: pathways.id
    relation_name: involved_in
    props: [source_type=constant:targets, target_type=constant:reactome, datasourceId, score, year, id]

  - source: diseaseId
    target: pathways.id
    relation: datatypeId
    props: [source_type=constant:disease, target_type=constant:reactome, datasourceId, score, year, id]

sourceId=uniprot_literature:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [source_type=constant:targets, target_type=constant:diseases, datasourceId, score, year, id]

sourceId=europepmc:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [source_type=constant:targets, target_type=constant:diseases, datasourceId, score, year, id]

sourceId=gene2phenotype:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [source_type=constant:targets, target_type=constant:diseases, datasourceId, score, year, id]

sourceId=impc:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [source_type=constant:targets, target_type=constant:diseases, datasourceId, score, year, id]

sourceId=uniprot_variants:
  source: targetId
  target: diseaseId
  relation: datatypeId
  props: [source_type=constant:targets, target_type=constant:diseases, datasourceId, score, year, id]
