interactionEvidence:
  source: targetA
  target: targetB
  relation_name: interacts_with
  props: [
    id,
    datasourceId=constant:interactionEvidence,
    score=constant:1.0,
    source_type=constant:targets,
    target_type=constant:targets
  ]

reactome:
  source: id
  target: parents
  relation_name: is_subpathway_of
  props: [
    id,
    datasourceId=constant:reactome,
    score=constant:1.0,
    source_type=constant:reactome,
    target_type=constant:reactome
  ]

diseases:
  source: id
  target: parents
  relation_name: is_subtype_of
  props: [
    id,
    datasourceId=constant:disease_ontology,
    score=constant:1.0,
    source_type=constant:diseases,
    target_type=constant:diseases
  ]

targets:
  source: id
  target: go
  relation_name: gene_ontology_annotation
  props: [
    id,
    datasourceId=constant:gene_ontology,
    score=constant:1.0,
    source_type=constant:targets,
    target_type=constant:go
  ]